#For agents and info sources
NUM_OF_AGENTS = 10
NUM_OF_INFO_SOURCES = 10
CONNECTIVITY_LEVEL = 0.1
TRUST_THRESHOLD = 0.5

#For information packets
NUM_OF_PACKETS = 1000
AVERAGE_SENTIMENT = 0.0
UNIQUE_TOPICS = 1
